version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: built dist folder
          command: |
            cd frontend
            npm i
            touch .env
            echo "VITE_APP_EMAILJS_SERVICE_ID='${VITE_APP_EMAILJS_SERVICE_ID}'" >.env
            echo "VITE_APP_EMAILJS_PUBLIC_KEY='${VITE_APP_EMAILJS_PUBLIC_KEY}'" >>.env
            echo "VITE_APP_EMAILJS_TEMPLATE_ID='${VITE_APP_EMAILJS_TEMPLATE_ID}'" >>.env
            npm run build -- --mode production
      - persist_to_workspace:
          root: frontend
          paths:
            - dist

  deploy:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/frontend
      - run: rsync -r -t -p -v --progress -e 'ssh -i ~/.ssh/id_rsa' -s frontend/dist/ ${SSH_USER}@${SERVER_IP}:/usr/share/nginx/html

workflows:
  version: 2
  untagged_build_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
