version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:21.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: built dist folder
          command: |
            cd frontend
            npm i
            touch .env
            echo "VITE_APP_EMAILJS_SERVICE_ID='${VITE_APP_EMAILJS_SERVICE_ID}'" >.env
            echo "VITE_APP_EMAILJS_PUBLIC_KEY='${VITE_APP_EMAILJS_PUBLIC_KEY}'" >>.env
            echo "VITE_APP_EMAILJS_TEMPLATE_ID='${VITE_APP_EMAILJS_TEMPLATE_ID}'" >>.env
            npm run build -- --mode production
      - persist_to_workspace:
          root: frontend
          paths:
            - dist

  build-backend:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and tag wg-vpn image
          command: |
            cd ~/repo/backend
            docker build -t website-backend:$CIRCLE_TAG .
            docker tag website-backend:$CIRCLE_TAG $IMAGE_NAME:latest

  git-leaks:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run -v ~/repo:/path zricethezav/gitleaks:latest detect --source="/path" -v

  deploy-frontend:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/frontend
      - run: rsync -r -t -p -v --progress -e 'ssh -i ~/.ssh/id_rsa' -s frontend/dist/ ${SSH_USER}@${SERVER_IP}:/usr/share/nginx/html

workflows:
  version: 2
  untagged_build_test:
    jobs:
      - build-frontend
      - build-backend
      - git-leaks
      - deploy-frontend:
          requires:
            - build-frontend
            - git-leaks
