version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run:
          name: built dist folder
          command: |
            cd frontend
            npm i
            npm run build -- --mode production
      - run: rsync -r -t -p -v --progress -e 'ssh -i ~/.ssh/id_rsa' -s frontend/dist/ ${SSH_USER}@${SERVER_IP}:/usr/share/nginx/html

workflows:
  version: 2
  untagged_build_test:
    jobs:
      - build
