---
- name: Deploy Backend to remote
  hosts: remote_server
  gather_facts: true
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Deploy BE | ensure docker compose in /home/
      ansible.builtin.template:
        src: compose.yml.j2
        dest: /home/docker-compose.yml
        owner: root
        group: wheel
        mode: '0644'

    - name: Deploy BE | Load all image(s) from the given tar file
      community.docker.docker_image_load:
        path: /tmp/website-backend.tar
      register: result

    - name: Deploy BE | Print the loaded image names
      ansible.builtin.debug:
        msg: "Loaded the following images: {{ result.image_names | join(', ') }}"

    - name: Deploy BE | Prune everything (including non-dangling images)
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
